# Generated by Django 5.0.2 on 2025-12-02 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=6, unique=True)),
                ('nombre_materia', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=3)),
                ('dias', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=15)),
                ('programa_educativo', models.CharField(choices=[('ICC', 'Ingeniería en Ciencias de la Computación'), ('LCC', 'Licenciatura en Ciencias de la Computación'), ('ITI', 'Ingeniería en Tecnologías de la Información')], max_length=3)),
                ('creditos', models.PositiveIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='app_escolar_api.maestros')),
            ],
        ),
    ]
